apiVersion: v1
kind: Secret
metadata:
  name: tasky-secrets
  namespace: tasky
  labels:
    app.kubernetes.io/name: tasky
    app.kubernetes.io/part-of: tasky-app
type: Opaque
data:
  # Base64 encoded values - these will be updated after Terraform deployment
  # MONGODB_URI: mongodb://taskyadmin:TaskySecure123!@<mongodb-ip>:27017/tasky
  mongodb-uri: (this is a placeholder, will be updated)
  # SECRET_KEY: tasky-jwt-secret-key-for-insight-exercise
  jwt-secret: (this is a placeholder, will be updated)
