apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: tasky
  labels:
    app.kubernetes.io/name: tasky
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: tasky-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: tasky
    app.kubernetes.io/component: web
